/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAnalyticsRouteImport } from './routes/student.analytics'
import { Route as StudentBrainRouteImport } from './routes/student.brain'
import { Route as StudentGraphRouteImport } from './routes/student.graph'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as TeacherNotesRouteImport } from './routes/teacher.notes'
import { Route as StudentClassroomsIndexRouteImport } from './routes/student.classrooms.index'
import { Route as StudentClassroomsIdRouteImport } from './routes/student.classrooms.$id'
import { Route as StudentNotesIdRouteImport } from './routes/student.notes.$id'
import { Route as StudentTestsIdRouteImport } from './routes/student.tests.$id'
import { Route as TeacherClassroomsIndexRouteImport } from './routes/teacher.classrooms.index'
import { Route as TeacherClassroomsIdRouteImport } from './routes/teacher.classrooms.$id'
import { Route as TeacherTestsIndexRouteImport } from './routes/teacher.tests.index'
import { Route as TeacherTestsNewRouteImport } from './routes/teacher.tests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAnalyticsRoute = StudentAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBrainRoute = StudentBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGraphRoute = StudentGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotesRoute = TeacherNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentClassroomsIndexRoute = StudentClassroomsIndexRouteImport.update({
  id: '/classrooms/',
  path: '/classrooms/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentClassroomsIdRoute = StudentClassroomsIdRouteImport.update({
  id: '/classrooms/$id',
  path: '/classrooms/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotesIdRoute = StudentNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTestsIdRoute = StudentTestsIdRouteImport.update({
  id: '/tests/$id',
  path: '/tests/$id',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherClassroomsIndexRoute = TeacherClassroomsIndexRouteImport.update({
  id: '/classrooms/',
  path: '/classrooms/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassroomsIdRoute = TeacherClassroomsIdRouteImport.update({
  id: '/classrooms/$id',
  path: '/classrooms/$id',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestsIndexRoute = TeacherTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestsNewRoute = TeacherTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/brain': typeof StudentBrainRoute
  '/student/graph': typeof StudentGraphRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/classrooms/$id': typeof StudentClassroomsIdRoute
  '/student/notes/$id': typeof StudentNotesIdRoute
  '/student/tests/$id': typeof StudentTestsIdRoute
  '/teacher/classrooms/$id': typeof TeacherClassroomsIdRoute
  '/teacher/tests/new': typeof TeacherTestsNewRoute
  '/student/classrooms/': typeof StudentClassroomsIndexRoute
  '/teacher/classrooms/': typeof TeacherClassroomsIndexRoute
  '/teacher/tests/': typeof TeacherTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/brain': typeof StudentBrainRoute
  '/student/graph': typeof StudentGraphRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/classrooms/$id': typeof StudentClassroomsIdRoute
  '/student/notes/$id': typeof StudentNotesIdRoute
  '/student/tests/$id': typeof StudentTestsIdRoute
  '/teacher/classrooms/$id': typeof TeacherClassroomsIdRoute
  '/teacher/tests/new': typeof TeacherTestsNewRoute
  '/student/classrooms': typeof StudentClassroomsIndexRoute
  '/teacher/classrooms': typeof TeacherClassroomsIndexRoute
  '/teacher/tests': typeof TeacherTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/brain': typeof StudentBrainRoute
  '/student/graph': typeof StudentGraphRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/classrooms/$id': typeof StudentClassroomsIdRoute
  '/student/notes/$id': typeof StudentNotesIdRoute
  '/student/tests/$id': typeof StudentTestsIdRoute
  '/teacher/classrooms/$id': typeof TeacherClassroomsIdRoute
  '/teacher/tests/new': typeof TeacherTestsNewRoute
  '/student/classrooms/': typeof StudentClassroomsIndexRoute
  '/teacher/classrooms/': typeof TeacherClassroomsIndexRoute
  '/teacher/tests/': typeof TeacherTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/analytics'
    | '/student/brain'
    | '/student/graph'
    | '/teacher/analytics'
    | '/teacher/notes'
    | '/student/'
    | '/teacher/'
    | '/student/classrooms/$id'
    | '/student/notes/$id'
    | '/student/tests/$id'
    | '/teacher/classrooms/$id'
    | '/teacher/tests/new'
    | '/student/classrooms/'
    | '/teacher/classrooms/'
    | '/teacher/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/analytics'
    | '/student/brain'
    | '/student/graph'
    | '/teacher/analytics'
    | '/teacher/notes'
    | '/student'
    | '/teacher'
    | '/student/classrooms/$id'
    | '/student/notes/$id'
    | '/student/tests/$id'
    | '/teacher/classrooms/$id'
    | '/teacher/tests/new'
    | '/student/classrooms'
    | '/teacher/classrooms'
    | '/teacher/tests'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/analytics'
    | '/student/brain'
    | '/student/graph'
    | '/teacher/analytics'
    | '/teacher/notes'
    | '/student/'
    | '/teacher/'
    | '/student/classrooms/$id'
    | '/student/notes/$id'
    | '/student/tests/$id'
    | '/teacher/classrooms/$id'
    | '/teacher/tests/new'
    | '/student/classrooms/'
    | '/teacher/classrooms/'
    | '/teacher/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/analytics': {
      id: '/student/analytics'
      path: '/analytics'
      fullPath: '/student/analytics'
      preLoaderRoute: typeof StudentAnalyticsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/brain': {
      id: '/student/brain'
      path: '/brain'
      fullPath: '/student/brain'
      preLoaderRoute: typeof StudentBrainRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/graph': {
      id: '/student/graph'
      path: '/graph'
      fullPath: '/student/graph'
      preLoaderRoute: typeof StudentGraphRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analytics': {
      id: '/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof TeacherAnalyticsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notes': {
      id: '/teacher/notes'
      path: '/notes'
      fullPath: '/teacher/notes'
      preLoaderRoute: typeof TeacherNotesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/classrooms/': {
      id: '/student/classrooms/'
      path: '/classrooms'
      fullPath: '/student/classrooms/'
      preLoaderRoute: typeof StudentClassroomsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/classrooms/$id': {
      id: '/student/classrooms/$id'
      path: '/classrooms/$id'
      fullPath: '/student/classrooms/$id'
      preLoaderRoute: typeof StudentClassroomsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notes/$id': {
      id: '/student/notes/$id'
      path: '/notes/$id'
      fullPath: '/student/notes/$id'
      preLoaderRoute: typeof StudentNotesIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tests/$id': {
      id: '/student/tests/$id'
      path: '/tests/$id'
      fullPath: '/student/tests/$id'
      preLoaderRoute: typeof StudentTestsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/classrooms/': {
      id: '/teacher/classrooms/'
      path: '/classrooms'
      fullPath: '/teacher/classrooms/'
      preLoaderRoute: typeof TeacherClassroomsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classrooms/$id': {
      id: '/teacher/classrooms/$id'
      path: '/classrooms/$id'
      fullPath: '/teacher/classrooms/$id'
      preLoaderRoute: typeof TeacherClassroomsIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/tests/': {
      id: '/teacher/tests/'
      path: '/tests'
      fullPath: '/teacher/tests/'
      preLoaderRoute: typeof TeacherTestsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/tests/new': {
      id: '/teacher/tests/new'
      path: '/tests/new'
      fullPath: '/teacher/tests/new'
      preLoaderRoute: typeof TeacherTestsNewRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface StudentRouteChildren {
  StudentAnalyticsRoute: typeof StudentAnalyticsRoute
  StudentBrainRoute: typeof StudentBrainRoute
  StudentGraphRoute: typeof StudentGraphRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentClassroomsIdRoute: typeof StudentClassroomsIdRoute
  StudentNotesIdRoute: typeof StudentNotesIdRoute
  StudentTestsIdRoute: typeof StudentTestsIdRoute
  StudentClassroomsIndexRoute: typeof StudentClassroomsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAnalyticsRoute: StudentAnalyticsRoute,
  StudentBrainRoute: StudentBrainRoute,
  StudentGraphRoute: StudentGraphRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentClassroomsIdRoute: StudentClassroomsIdRoute,
  StudentNotesIdRoute: StudentNotesIdRoute,
  StudentTestsIdRoute: StudentTestsIdRoute,
  StudentClassroomsIndexRoute: StudentClassroomsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnalyticsRoute: typeof TeacherAnalyticsRoute
  TeacherNotesRoute: typeof TeacherNotesRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassroomsIdRoute: typeof TeacherClassroomsIdRoute
  TeacherTestsNewRoute: typeof TeacherTestsNewRoute
  TeacherClassroomsIndexRoute: typeof TeacherClassroomsIndexRoute
  TeacherTestsIndexRoute: typeof TeacherTestsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnalyticsRoute: TeacherAnalyticsRoute,
  TeacherNotesRoute: TeacherNotesRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassroomsIdRoute: TeacherClassroomsIdRoute,
  TeacherTestsNewRoute: TeacherTestsNewRoute,
  TeacherClassroomsIndexRoute: TeacherClassroomsIndexRoute,
  TeacherTestsIndexRoute: TeacherTestsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
